# Generated by Django 6.0.7 on 2026-07-30 23:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=200)),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('cycle_used_hours', models.FloatField(default=0.0)),
                ('start_datetime', models.DateTimeField()),
                ('driver_name', models.CharField(blank=True, max_length=120)),
                ('carrier_name', models.CharField(blank=True, max_length=120)),
                ('main_office', models.CharField(blank=True, max_length=200)),
                ('truck_number', models.CharField(blank=True, max_length=60)),
                ('trailer_number', models.CharField(blank=True, max_length=60)),
                ('shipper', models.CharField(blank=True, max_length=120)),
                ('commodity', models.CharField(blank=True, max_length=120)),
                ('load_id', models.CharField(blank=True, max_length=60)),
                ('co_driver', models.CharField(blank=True, max_length=120)),
                ('total_miles', models.FloatField(default=0.0)),
                ('driving_minutes', models.IntegerField(default=0)),
                ('elapsed_minutes', models.IntegerField(default=0)),
                ('log_days', models.IntegerField(default=0)),
                ('is_compliant', models.BooleanField(default=True)),
                ('route_source', models.CharField(default='osrm', max_length=20)),
                ('plan', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_trip_created_24deb9_idx'), models.Index(fields=['is_compliant'], name='api_trip_is_comp_09d3fd_idx')],
            },
        ),
    ]
